### ISSUE TITLE
发现还是要开发功能，和 Editor.md 比还需要完善

### ISSUE THREAD

**Issue by jerviscui** [xyhuai/Wiz.Vditor#1]

**Comment by WolfMoss** [comment]
嗯，主要是根据我的个人写作习惯集成了最简单的所见即所得和读写功能，因为体会不到别人的需求就没有加其他的东西。不过大部分功能在开源的Vditor应该都有了，只在于是否配置上，如果有想法可以具体提一下，我没项目的时候会加的
![image](https://user-images.githubusercontent.com/49391241/106272997-e309ea80-626c-11eb-849b-e844d97e8969.png)

**Comment by jerviscui** [comment]
非常感谢。
我都是用一栏编辑，一栏预览的方式，所见所得还不太习惯。
看到很多新功能，比如脑图。
