### ISSUE TITLE
能不能在点完上传图片之后，默认输入一句

### ISSUE THREAD

**Issue by NightmareZero** [xyhuai/Wiz.Vditor#4]
`![](index_files/v2-a8f245e81fea7c513b3b59f44b940db6_1440w.jpg)`

这种的

`![](index_files/$上传的文件名)`

**Comment by WolfMoss** [comment]
可以直接CTRL+V的,就会出来了

**Comment by NightmareZero** [comment]
> 可以直接CTRL+V的,就会出来了

我试过了，没有任何反应，按ctrl+v还是原来的，剪贴板没有任何变化

不对，是上传直接就不可用了，自己填 `![](index_files/$上传的文件名)` 图片 也是破的

**Comment by WolfMoss** [comment]
> > 可以直接CTRL+V的,就会出来了
> 
> 我试过了，没有任何反应，按ctrl+v还是原来的，剪贴板没有任何变化

还是原来的？具体是什么？复制图片后，在编辑器里ctrl+v，出来的不是图片地址吗？
